### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by 178inaba** [KilledByNLP/twitter-icon-rotator-chrome-extension#14]
**Demo** and **Install stable version** link is dead.
https://pic.twitter.com/43awWbYSN8
https://chrome.google.com/webstore/detail/twitter-icon-rotator/khkdnpcopeccjcnpmlfmnjmfnfhfnpgh

**Comment by iwasa-kosui** [comment]
Thank you @178inaba san!
I will fix it.

**Comment by iwasa-kosui** [comment]
fixed. thanks!
